//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDeskUser
    {
        public int DUE_ID { get; set; }
        public int DUE_USE_ID { get; set; }
        public System.DateTime DUE_REGISTTIME { get; set; }
        public string DUE_REALNAME { get; set; }
        public string DUE_PHONE { get; set; }
        public string DUE_USERDSPNAME { get; set; }
        public Nullable<int> DUE_SEX { get; set; }
        public string DUE_EMAIL { get; set; }
        public int DUE_SUT_ID { get; set; }
    }
}
