//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDrawMoney
    {
        public int DAM_ID { get; set; }
        public int DAM_DUE_ID { get; set; }
        public System.DateTime DAM_CREATETIME { get; set; }
        public decimal DAM_MONEY { get; set; }
        public string DAM_DESC { get; set; }
        public int DAW_STATE { get; set; }
        public int DAW_MST_ID { get; set; }
        public Nullable<System.DateTime> DAW_CONFIRMTIME { get; set; }
    }
}
