//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOperationLog
    {
        public int OPL_ID { get; set; }
        public Nullable<int> OPL_USE_ID { get; set; }
        public string OPL_TITLE { get; set; }
        public string OPL_DESC { get; set; }
        public Nullable<System.DateTime> OPL_CREATETIME { get; set; }
    }
}
