//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSSC
    {
        public int SSC_ID { get; set; }
        public string SSC_NO { get; set; }
        public string SSC_NUMBER { get; set; }
        public System.DateTime SSC_DATE { get; set; }
        public Nullable<System.DateTime> SSC_WRITEDT { get; set; }
        public Nullable<int> SSC_STATE { get; set; }
    }
}
