//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSSC_DUE_BUY
    {
        public int SCD_ID { get; set; }
        public int SCD_DUE_ID { get; set; }
        public int SCD_DAT_ID { get; set; }
        public System.DateTime SCD_DATE { get; set; }
        public System.DateTime SCD_SCC_NO { get; set; }
        public string SCD_NUMBERS { get; set; }
        public int SCD_TIMES { get; set; }
        public int SCD_STATE { get; set; }
    }
}
