//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUser
    {
        public int USE_ID { get; set; }
        public string USE_NAME { get; set; }
        public string USE_PASSWORD { get; set; }
        public bool USE_ACTIVITY { get; set; }
        public int USE_UGP_ID { get; set; }
    }
}
