//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayOnLine
    {
        public int POL_ID { get; set; }
        public System.DateTime POL_CREATETIME { get; set; }
        public int POL_DAT_ID { get; set; }
        public decimal POL_MONEY { get; set; }
        public int POL_USE_ID { get; set; }
        public string POL_STATE { get; set; }
        public Nullable<System.DateTime> POL_CONFIRMTIME { get; set; }
    }
}
