//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMenu
    {
        public int MNU_ID { get; set; }
        public string MNU_TEXTCN { get; set; }
        public string MNU_TEXTEN { get; set; }
        public Nullable<int> MNU_PARENTID { get; set; }
        public Nullable<int> MNU_SORT { get; set; }
        public string MNU_URL { get; set; }
        public string MNU_IMGURL { get; set; }
    }
}
