//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Repository
{
    using Lottery.Core.DataModel;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LotteryContext : DbContext
    {
        public LotteryContext()
            : base("name=LotteryContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BChangeMoney> BChangeMoney { get; set; }
        public virtual DbSet<BDeskUser> BDeskUser { get; set; }
        public virtual DbSet<BDrawMoney> BDrawMoney { get; set; }
        public virtual DbSet<BLoginLog> BLoginLog { get; set; }
        public virtual DbSet<BMasters> BMasters { get; set; }
        public virtual DbSet<BMessage> BMessage { get; set; }
        public virtual DbSet<BOperationLog> BOperationLog { get; set; }
        public virtual DbSet<BUser> BUser { get; set; }
        public virtual DbSet<BUserBankCard> BUserBankCard { get; set; }
        public virtual DbSet<BUserGroup> BUserGroup { get; set; }
        public virtual DbSet<BUserMoney> BUserMoney { get; set; }
        public virtual DbSet<BUserType> BUserType { get; set; }
        public virtual DbSet<PayOnLine> PayOnLine { get; set; }
        public virtual DbSet<PReceiveMsg> PReceiveMsg { get; set; }
        public virtual DbSet<PSendMsg> PSendMsg { get; set; }
        public virtual DbSet<SDealType> SDealType { get; set; }
        public virtual DbSet<SMasterRoles> SMasterRoles { get; set; }
        public virtual DbSet<SMenu> SMenu { get; set; }
        public virtual DbSet<SMenuPermission> SMenuPermission { get; set; }
        public virtual DbSet<SRoleMenu> SRoleMenu { get; set; }
        public virtual DbSet<SRolePermission> SRolePermission { get; set; }
        public virtual DbSet<SRoles> SRoles { get; set; }
        public virtual DbSet<SPermission> SPermission { get; set; }
    }
}
